server {
    listen 80;

    server_name localhost;

    location / {
        proxy_pass http://django_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'test_db'),
        'USER': os.getenv('MYSQL_USER', 'root'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'root'),
        'HOST': os.getenv('MYSQL_HOST', 'db'),
        'PORT': '3306',
    }
}
healthcheck:
  test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=test_db
MYSQL_USER=root
MYSQL_PASSWORD=root
db:
  ...
  env_file:
    - .env
django_app:
  ...
  env_file:
    - .env

